"""Extensible, declarative architecture intermediate representation."""

from architecture_ir.codec import IRDecodeError, decode_graph_json, encode_graph_json
from architecture_ir.graph import (
    ArchitectureGraph,
    CustomPrimitiveSpec,
    EdgeKind,
    IREdge,
    IRNode,
    PrimitiveKind,
    TensorShape,
    ValidationIssue,
    ValidationResult,
    validate_graph,
)
from architecture_ir.interpreter import (
    DEFAULT_LIMITS,
    PHASE1_VOCAB_SIZE,
    IRCandidateValidation,
    IRInterpreterError,
    InterpretedCandidate,
    InterpreterIssue,
    InterpreterLimits,
    load_and_build_ir_candidate,
    validate_ir_candidate_json,
    validate_ir_candidate_path,
)
from architecture_ir.runtime_evidence import (
    FreshBuildEvidence,
    RuntimeBindings,
    RuntimeValidityEvidence,
    probe_fresh_build,
    probe_runtime_validity,
)

__all__ = [
    "ArchitectureGraph",
    "CustomPrimitiveSpec",
    "EdgeKind",
    "FreshBuildEvidence",
    "IREdge",
    "IRDecodeError",
    "IRCandidateValidation",
    "IRInterpreterError",
    "IRNode",
    "InterpretedCandidate",
    "InterpreterIssue",
    "InterpreterLimits",
    "DEFAULT_LIMITS",
    "PHASE1_VOCAB_SIZE",
    "PrimitiveKind",
    "RuntimeBindings",
    "RuntimeValidityEvidence",
    "TensorShape",
    "ValidationIssue",
    "ValidationResult",
    "decode_graph_json",
    "encode_graph_json",
    "load_and_build_ir_candidate",
    "probe_fresh_build",
    "probe_runtime_validity",
    "validate_graph",
    "validate_ir_candidate_json",
    "validate_ir_candidate_path",
]
